name: dadjokes
description: A collection of terrible jokes.

dependencies:
  flutter:
    sdk: flutter
  http: "^0.11.3+16"
  share: "^0.4.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Patrick Hand
      fonts:
       - asset: assets/fonts/PatrickHand-Regular.ttf
